if(NOT DEFINED SOURCE_DIR)
    message(FATAL_ERROR "SOURCE_DIR is required")
endif()

function(read_source relative_path output_variable)
    file(READ "${SOURCE_DIR}/${relative_path}" source)
    set(${output_variable} "${source}" PARENT_SCOPE)
endfunction()

read_source("package/contents/ui/TodoBoard.qml" todo_board)
read_source("package/contents/ui/TaskCard.qml" task_card)
read_source("package/contents/ui/CategoryHeader.qml" category_header)
read_source("package/contents/ui/TaskDetails.qml" task_details)
read_source("package/contents/ui/ReportsView.qml" reports_view)
read_source("package/contents/ui/DailyTimeline.qml" daily_timeline)
read_source("package/contents/ui/YearHeatmap.qml" year_heatmap)
read_source("package/contents/ui/SettingsPage.qml" settings_page)
read_source("package/contents/ui/ConfigGeneral.qml" config_general)
read_source("package/contents/config/main.xml" config_xml)

# Dialog enum assignments caused the widget to fail loading before any action
# could be used. Zero is not a valid QML enum assignment for standardButtons.
foreach(source IN ITEMS "${todo_board}" "${task_details}" "${reports_view}")
    if(source MATCHES "standardButtons:[ \t]*0")
        message(FATAL_ERROR "Dialogs must omit standardButtons when no standard button is required")
    endif()
endforeach()

# Plasmoid overlays require an explicit visual parent; ApplicationWindow's
# implicit overlay is unavailable in this component hierarchy.
if(todo_board MATCHES "Controls\\.Dialog[^{]*\\{[^}]*parent:[ \t]*root\\.parent")
    message(FATAL_ERROR "TodoBoard dialogs must be parented to TodoBoard")
endif()
if(task_details MATCHES "parent:[ \t]*root\\.parent" OR reports_view MATCHES "parent:[ \t]*root\\.parent")
    message(FATAL_ERROR "Nested dialogs must not rely on a parent dialog's QObject parent")
endif()
if(NOT task_details MATCHES "parent:[ \t]*popupHost")
    message(FATAL_ERROR "Task-details overlays must use the page popup host")
endif()
if(NOT reports_view MATCHES "FocusScope" OR NOT todo_board MATCHES "currentPage === \"reports\"" OR NOT todo_board MATCHES "onBackRequested:[ \t]*root\\.closeReports")
    message(FATAL_ERROR "Reports must remain an in-place navigation page")
endif()

# Report visualizations must retain every approved entry point and preserve
# quarter-hour interaction plus heatmap day drill-down.
if(NOT todo_board MATCHES "daily-timeline-header" OR NOT category_header MATCHES "category-timeline-" OR NOT task_details MATCHES "DailyTimeline")
    message(FATAL_ERROR "Daily timeline must be reachable from the header, category, and task details")
endif()
if(NOT daily_timeline MATCHES "slotCount" OR NOT daily_timeline MATCHES "sessionCreateRequested" OR NOT daily_timeline MATCHES "sessionEditRequested")
    message(FATAL_ERROR "Daily timeline must use interactive 15-minute slots")
endif()
if(NOT daily_timeline MATCHES "buildSegmentLayout" OR NOT daily_timeline MATCHES "laneCount" OR NOT daily_timeline MATCHES "zoom-in" OR NOT daily_timeline MATCHES "preventStealing" OR NOT daily_timeline MATCHES "interactive:[ \\t]*!root\\.creationEnabled")
    message(FATAL_ERROR "Daily timeline must stack concurrent sessions, support zoom, and protect drawing gestures")
endif()
if(NOT reports_view MATCHES "YearHeatmap" OR NOT year_heatmap MATCHES "daySelected" OR NOT reports_view MATCHES "\"year\"")
    message(FATAL_ERROR "Reports must provide a yearly heatmap with daily drill-down")
endif()
if(NOT reports_view MATCHES "Loader" OR NOT reports_view MATCHES "active:[ \t]*root\\.report !== null" OR NOT daily_timeline MATCHES "rawSlotCount >= 92" OR NOT daily_timeline MATCHES "rawSlotCount <= 100")
    message(FATAL_ERROR "Report visualizations must be lazy and daily timelines must have bounded slot counts")
endif()

# TaskDetails is a separate component, so it cannot access TodoBoard's private
# ListModel ID. Keep the explicit public alias and consume that API.
if(NOT todo_board MATCHES "property alias categories:[ \t]*categoryModel")
    message(FATAL_ERROR "TodoBoard must expose its category model to TaskDetails")
endif()
if(task_details MATCHES "board\\.categoryModel" OR NOT task_details MATCHES "board\\.categories")
    message(FATAL_ERROR "TaskDetails must use TodoBoard's public categories model")
endif()

# Task editing is an in-place page. The card body, not a redundant pencil icon,
# opens it while timer, drag, and overflow controls retain their own actions.
if(NOT task_details MATCHES "FocusScope" OR NOT task_details MATCHES "function loadTask" OR NOT task_details MATCHES "function requestClose")
    message(FATAL_ERROR "TaskDetails must remain an in-place details page")
endif()
if(NOT task_details MATCHES "hasUnsavedChanges")
    message(FATAL_ERROR "TaskDetails must expose unsaved-change state for guarded navigation")
endif()
if(NOT todo_board MATCHES "property string currentPage" OR NOT todo_board MATCHES "function openTask" OR NOT todo_board MATCHES "function requestTaskDetailsClose" OR NOT todo_board MATCHES "onOpenRequested:[ \t]*root\\.openTask")
    message(FATAL_ERROR "TodoBoard must route card activation to the details page")
endif()
if(task_card MATCHES "icon\\.name:[ \t]*\"document-edit\"")
    message(FATAL_ERROR "Task cards must not expose a redundant edit button")
endif()
if(NOT task_card MATCHES "onTapped:[ \t]*root\\.openRequested\\(\\)")
    message(FATAL_ERROR "Task information must retain a details-page tap handler")
endif()
if(NOT task_card MATCHES "taskActionsMenu\\.popup\\(taskActionsButton, 0, taskActionsButton\\.height\\)")
    message(FATAL_ERROR "Task action menu must be anchored to its button")
endif()
if(NOT category_header MATCHES "categoryActionsMenu\\.popup\\(categoryActionsButton, 0, categoryActionsButton\\.height\\)")
    message(FATAL_ERROR "Category action menu must be anchored to its button")
endif()

# Reorder handles must use an icon available in Breeze. A floating source plus
# live model preview must support before/after and terminal insertion points.
foreach(source IN ITEMS "${task_card}" "${category_header}")
    if(source MATCHES "openhand-cursor" OR source MATCHES "edit-move")
        message(FATAL_ERROR "Drag handles must use the Breeze drag-handle-symbolic icon")
    endif()
    if(NOT source MATCHES "icon\\.name:[ \t]*\"drag-handle-symbolic\"")
        message(FATAL_ERROR "Drag handles must use the Breeze drag-handle-symbolic icon")
    endif()
    if(NOT source MATCHES "target:[ \t]*root" OR NOT source MATCHES "dragOriginX" OR NOT source MATCHES "root\\.Drag\\.drop\\(\\)")
        message(FATAL_ERROR "Drag handlers must restore their Repeater-managed source after each drop")
    endif()
endforeach()
if(NOT task_card MATCHES "dragPreviewRequested" OR NOT task_card MATCHES "placementFor")
    message(FATAL_ERROR "Task drag targets must preview before and after placement")
endif()
if(NOT category_header MATCHES "dragPreviewRequested" OR NOT category_header MATCHES "taskPreviewRequested" OR NOT category_header MATCHES "placementFor")
    message(FATAL_ERROR "Category drag targets must preview task and category placement")
endif()
if(NOT todo_board MATCHES "function previewTaskMove" OR NOT todo_board MATCHES "function previewCategoryMove" OR NOT todo_board MATCHES "commitTaskDrop" OR NOT todo_board MATCHES "commitCategoryDrop" OR NOT todo_board MATCHES "finally")
    message(FATAL_ERROR "Move operations must preview and reload persisted ordering after failures")
endif()
if(NOT todo_board MATCHES "draggedTaskData \\? root\\.draggedTaskData\\.title" OR NOT todo_board MATCHES "draggedCategoryData \\? root\\.draggedCategoryData\\.name")
    message(FATAL_ERROR "Drag placeholders must retain the dragged item data instead of using the hover target")
endif()
if(NOT category_header MATCHES "property var dragGroup" OR NOT category_header MATCHES "target:[ \\t]*root")
    message(FATAL_ERROR "Category drag must retain a live Drag-attached header and category-group metadata")
endif()
if(NOT todo_board MATCHES "draggedCategoryTasks" OR NOT todo_board MATCHES "CategoryDragGroup" OR NOT todo_board MATCHES "dragGroup: categorySlot")
    message(FATAL_ERROR "Category drag previews must reuse full category groups")
endif()
if(NOT category_header MATCHES "property bool interactive" OR NOT task_card MATCHES "property bool interactive" OR NOT todo_board MATCHES "category-drag-preview")
    message(FATAL_ERROR "Category drag ghosts must reuse passive live components")
endif()
if(NOT todo_board MATCHES "readonly property bool draggingSource" OR NOT todo_board MATCHES "height: draggingSource \\? 0 : implicitHeight" OR NOT todo_board MATCHES "category-drag-placeholder-" OR NOT todo_board MATCHES "opacity: 0.55")
    message(FATAL_ERROR "Category drag must collapse the source and insert one full-fidelity destination ghost")
endif()
if(NOT todo_board MATCHES "category-drag-preview-frame" OR NOT todo_board MATCHES "opacity: 0.85" OR NOT todo_board MATCHES "border.color: Kirigami.Theme.highlightColor")
    message(FATAL_ERROR "Category drag ghosts must retain a translucent highlighted frame")
endif()
if(NOT todo_board MATCHES "category-drop-target-" OR NOT todo_board MATCHES "height: categorySlot\\.implicitHeight")
    message(FATAL_ERROR "Category drops must cover the complete destination group, including its task cards")
endif()

# Concurrent timers are disabled by default, configured from either settings
# surface, and resolved explicitly before reducing multiple active timers.
if(NOT config_xml MATCHES "entry name=\"allowConcurrentTimers\" type=\"Bool\"" OR NOT config_xml MATCHES "<default>false</default>")
    message(FATAL_ERROR "Concurrent timers must be a persisted preference disabled by default")
endif()
if(NOT config_general MATCHES "cfg_allowConcurrentTimers" OR NOT settings_page MATCHES "allowConcurrentTimers")
    message(FATAL_ERROR "Both settings surfaces must expose the concurrent timer preference")
endif()
if(NOT todo_board MATCHES "function requestConcurrentTimersChange" OR NOT todo_board MATCHES "stopTimersExcept" OR NOT todo_board MATCHES "concurrent-timer-resolution" OR NOT todo_board MATCHES "Controls\.Popup\.NoAutoClose")
    message(FATAL_ERROR "Disabling concurrent timers must require explicit active-timer resolution")
endif()
if(NOT todo_board MATCHES "getActiveSessions" OR NOT todo_board MATCHES "isTaskActive" OR NOT task_details MATCHES "board\.isTaskActive")
    message(FATAL_ERROR "Timer UI must support task-scoped concurrent active sessions")
endif()
